### ISSUE TITLE
PIConGPU version

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu-workshop#10]
The version in `software/picongpu/workshop` is `0.4.0`. I am assuming that will be at least bumped to `0.4.2`, but is there a chance for a `0.4.3` release from current `dev` before the workshop? IIRC some plugins were affected by recent commits.

Either way, I'd like to know which version to test the notebooks on :)

**Comment by ax3l** [comment]
Yes, there will be a 0.4.3 soon, fixing minor bugs in 0.4.2

**Comment by berceanu** [comment]
OK, so I will target the notebooks at the current `dev` then.

**Comment by n01r** [comment]
I was thinking that we could basically represent different workshops by different branches of the picongpu-workshop repository. Dunno if we would even upload the code version here after the workshop.

**Comment by ax3l** [comment]
0.4.3 is nearly ready in https://github.com/ComputationalRadiationPhysics/picongpu/pull/2885

**Comment by ax3l** [comment]
> different branches of the picongpu-workshop repository

let's start with the current workshop and tag it when it's over.

new workshops just update old workshop branches, like we do in real life :) (then they are tagged again)

**Comment by n01r** [comment]
that's how I thought about doing it - basically like release branches in PIConGPU

**Comment by ax3l** [comment]
Yes, I just think that a rolling master is probably enough since we won't have parallel-y running workshops with different content :) That still allows to branch of "dead-end" forks for specific uses. Anyway, I trust you to find an efficient way.

**Comment by berceanu** [comment]
> parallel-y running workshops with different content

Now that's a concept!

**Comment by ax3l** [comment]
PIConGPU 0.4.3 is out now :)
