### ISSUE TITLE
`openpmd-api` install fails

### ISSUE THREAD

**Issue by berceanu** [ComputationalRadiationPhysics/picongpu-workshop#8]
Participants are instructed to install `openpmd-api` via `pip install -U --user openpmd-api` after sourcing `jupyter.profile`, which loads `cmake/3.10.1`.

`openpmd-api` [requires](https://github.com/openPMD/openPMD-api#dependencies) CMake 3.11.0+ and therefore the install fails.

I have not found a more recent module than `cmake/3.10.1`

**Comment by ax3l** [comment]
I will request a newer CMake for you (-> SR.8511)

**Comment by berceanu** [comment]
Shouldn't it be for all participants though, and not just for me? They are all expected to `pip install -U --user openpmd-api`, right?

**Comment by ax3l** [comment]
`cmake/3.13.4` is not available on Hypnos!

Yes, everyone installs in their own environment.

**Comment by berceanu** [comment]
`pip install -U --user openpmd-api`
`subprocess.CalledProcessError: Command '['cmake', '--version']' returned non-zero exit status 1.`
`cmake --version`
```
cmake: /opt/pkg/compiler/gnu/gcc/4.9.2/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by cmake)
cmake: /opt/pkg/compiler/gnu/gcc/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)
cmake: /opt/pkg/compiler/gnu/gcc/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by cmake)
```

**Comment by ax3l** [comment]
yes, also just realized and reported this as a bug... argh.

They have to re-build the module, will report when they managed to build a working module.

**Comment by berceanu** [comment]
Tested and working with `cmake 3.13.4`.

**Comment by berceanu** [comment]
Since I lack the permissions, can someone apply this patch to `/bigdata/hplsim/external/software/jupyter.profile`?

Workshop users are expected to copy that file to their `$HOME`.

[jupyter_profile_patch.txt](https://github.com/ComputationalRadiationPhysics/picongpu-workshop/files/2868651/jupyter_profile_patch.txt)

Should we also update `/bigdata/hplsim/external/software/k80_picongpu.profile` to use `cmake 3.13.4` for the workshop?

**Comment by ax3l** [comment]
Updated! Also updated the PIConGPU version to 0.4.3 in the `$PICSRC` of those profiles.

**Comment by berceanu** [comment]
@ax3l did you also update `/bigdata/hplsim/external/software/picongpu/workshop` to `0.4.3`?

**Comment by ax3l** [comment]
yep, it's a symlink.

allows us to patch upcoming problems during the workshop for all people.
